name: inventory_app
description: Offline-first stock-taking app.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.6.1
  go_router: ^10.2.0
  mobile_scanner: ^7.0.1
  drift: ^2.14.1
  sqlite3_flutter_libs: ^0.5.15
  path_provider: ^2.1.1
  share_plus: ^7.2.1
  intl: ^0.18.1
  uuid: ^3.0.7
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  drift_dev: ^2.14.1

flutter:
  uses-material-design: true
  assets:
    - assets/ 